In [7]:
import yfinance as yf
ticker = yf.Ticker("AAPL")

In [3]:
ticker.get_cash_flow()

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
FreeCashFlow,9.876700e+10,1.088070e+11,9.958400e+10,1.114430e+11,NaN
RepurchaseOfCapitalStock,-9.071100e+10,-9.494900e+10,-7.755000e+10,-8.940200e+10,NaN
RepaymentOfDebt,-1.093200e+10,-9.958000e+09,-1.115100e+10,-9.543000e+09,NaN
IssuanceOfDebt,4.481000e+09,0.000000e+00,5.228000e+09,5.465000e+09,NaN
IssuanceOfCapitalStock,NaN,NaN,NaN,NaN,1.105000e+09
CapitalExpenditure,-1.271500e+10,-9.447000e+09,-1.095900e+10,-1.070800e+10,NaN
InterestPaidSupplementalData,NaN,NaN,3.803000e+09,2.865000e+09,2.687000e+09
IncomeTaxPaidSupplementalData,4.336900e+10,2.610200e+10,1.867900e+10,1.957300e+10,NaN
EndCashPosition,3.593400e+10,2.994300e+10,3.073700e+10,2.497700e+10,NaN
BeginningCashPosition,2.994300e+10,3.073700e+10,2.497700e+10,3.592900e+10,NaN
ChangesInCash,5.991000e+09,-7.940000e+08,5.760000e+09,-1.095200e+10,NaN
FinancingCashFlow,-1.206860e+11,-1.219830e+11,-1.084880e+11,-1.107490e+11,NaN
CashFlowFromContinuingFinancingActivities,-1.206860e+11,-1.219830e+11,-1.084880e+11,-1.107490e+11,NaN
NetOtherFinancingCharges,-6.071000e+09,-5.802000e+09,-6.012000e+09,-6.383000e+09,NaN
CashDividendsPaid,-1.542100e+10,-1.523400e+10,-1.502500e+10,-1.484100e+10,NaN
CommonStockDividendPaid,-1.542100e+10,-1.523400e+10,-1.502500e+10,-1.484100e+10,NaN
NetCommonStockIssuance,-9.071100e+10,-9.494900e+10,-7.755000e+10,-8.940200e+10,NaN
CommonStockPayments,-9.071100e+10,-9.494900e+10,-7.755000e+10,-8.940200e+10,NaN
CommonStockIssuance,NaN,NaN,NaN,NaN,1.105000e+09
NetIssuancePaymentsOfDebt,-8.483000e+09,-5.998000e+09,-9.901000e+09,-1.230000e+08,NaN
NetShortTermDebtIssuance,-2.032000e+09,3.960000e+09,-3.978000e+09,3.955000e+09,NaN
NetLongTermDebtIssuance,-6.451000e+09,-9.958000e+09,-5.923000e+09,-4.078000e+09,NaN
LongTermDebtPayments,-1.093200e+10,-9.958000e+09,-1.115100e+10,-9.543000e+09,NaN
LongTermDebtIssuance,4.481000e+09,0.000000e+00,5.228000e+09,5.465000e+09,NaN
InvestingCashFlow,1.519500e+10,2.935000e+09,3.705000e+09,-2.235400e+10,NaN
CashFlowFromContinuingInvestingActivities,1.519500e+10,2.935000e+09,3.705000e+09,-2.235400e+10,NaN
NetOtherInvestingChanges,-1.480000e+09,-1.308000e+09,-1.337000e+09,-2.086000e+09,NaN
NetInvestmentPurchaseAndSale,2.939000e+10,1.369000e+10,1.600100e+10,-9.560000e+09,NaN
SaleOfInvestment,5.379700e+10,6.234600e+10,4.551400e+10,6.736300e+10,NaN
PurchaseOfInvestment,-2.440700e+10,-4.865600e+10,-2.951300e+10,-7.692300e+10,NaN
NetBusinessPurchaseAndSale,NaN,NaN,NaN,-3.060000e+08,-3.300000e+07
PurchaseOfBusiness,NaN,NaN,NaN,-3.060000e+08,-3.300000e+07
NetPPEPurchaseAndSale,-1.271500e+10,-9.447000e+09,-1.095900e+10,-1.070800e+10,NaN
PurchaseOfPPE,-1.271500e+10,-9.447000e+09,-1.095900e+10,-1.070800e+10,NaN
OperatingCashFlow,1.114820e+11,1.182540e+11,1.105430e+11,1.221510e+11,NaN
CashFlowFromContinuingOperatingActivities,1.114820e+11,1.182540e+11,1.105430e+11,1.221510e+11,NaN
ChangeInWorkingCapital,-2.500000e+10,3.651000e+09,-6.577000e+09,1.200000e+09,NaN
ChangeInOtherWorkingCapital,NaN,NaN,NaN,4.780000e+08,1.676000e+09
ChangeInOtherCurrentLiabilities,-1.107600e+10,1.555200e+10,3.031000e+09,6.110000e+09,NaN
ChangeInOtherCurrentAssets,-9.197000e+09,-1.173100e+10,-5.684000e+09,-6.499000e+09,NaN
ChangeInPayablesAndAccruedExpense,9.020000e+08,6.020000e+09,-1.889000e+09,9.448000e+09,NaN
ChangeInPayable,9.020000e+08,6.020000e+09,-1.889000e+09,9.448000e+09,NaN
ChangeInAccountPayable,9.020000e+08,6.020000e+09,-1.889000e+09,9.448000e+09,NaN
ChangeInInventory,1.400000e+09,-1.046000e+09,-1.618000e+09,1.484000e+09,NaN
ChangeInReceivables,-7.029000e+09,-5.144000e+09,-4.170000e+08,-9.343000e+09,NaN
ChangesInAccountReceivables,-6.682000e+09,-3.788000e+09,-1.688000e+09,-1.823000e+09,NaN
OtherNonCashItems,-8.900000e+07,-2.266000e+09,-2.227000e+09,1.006000e+09,NaN
StockBasedCompensation,1.286300e+10,1.168800e+10,1.083300e+10,9.038000e+09,NaN
DeferredTax,NaN,NaN,NaN,8.950000e+08,-4.774000e+09
DeferredIncomeTax,NaN,NaN,NaN,8.950000e+08,-4.774000e+09
DepreciationAmortizationDepletion,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
DepreciationAndAmortization,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
NetIncomeFromContinuingOperations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN

In [4]:
ticker.get_financials()

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
TaxEffectOfUnusualItems,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
TaxRateForCalcs,1.560000e-01,2.410000e-01,1.470000e-01,1.620000e-01,NaN
NormalizedEBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
NetIncomeFromContinuingOperationNetMinorityInterest,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
ReconciledDepreciation,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
ReconciledCostOfRevenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
EBIT,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
NetInterestIncome,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
InterestExpense,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
InterestIncome,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
NormalizedIncome,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
NetIncomeFromContinuingAndDiscontinuedOperation,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
TotalExpenses,2.831110e+11,2.678190e+11,2.689840e+11,2.748910e+11,NaN
TotalOperatingIncomeAsReported,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
DilutedAverageShares,1.500470e+10,1.540810e+10,1.581255e+10,1.632582e+10,NaN
BasicAverageShares,1.494850e+10,1.534378e+10,1.574423e+10,1.621596e+10,NaN
DilutedEPS,7.460000e+00,6.080000e+00,6.130000e+00,6.110000e+00,NaN
BasicEPS,7.490000e+00,6.110000e+00,6.160000e+00,6.150000e+00,NaN
DilutedNIAvailtoComStockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
NetIncomeCommonStockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
NetIncome,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
NetIncomeIncludingNoncontrollingInterests,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
NetIncomeContinuousOperations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
TaxProvision,2.071900e+10,2.974900e+10,1.674100e+10,1.930000e+10,NaN
PretaxIncome,1.327290e+11,1.234850e+11,1.137360e+11,1.191030e+11,NaN
OtherIncomeExpense,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
OtherNonOperatingIncomeExpenses,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
NetNonOperatingInterestIncomeExpense,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
InterestExpenseNonOperating,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
InterestIncomeNonOperating,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
OperatingIncome,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
OperatingExpense,6.215100e+10,5.746700e+10,5.484700e+10,5.134500e+10,NaN
ResearchAndDevelopment,3.455000e+10,3.137000e+10,2.991500e+10,2.625100e+10,NaN
SellingGeneralAndAdministration,2.760100e+10,2.609700e+10,2.493200e+10,2.509400e+10,NaN
GrossProfit,1.952010e+11,1.806830e+11,1.691480e+11,1.707820e+11,NaN
CostOfRevenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
TotalRevenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN
OperatingRevenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN

In [12]:
ticker.splits

Date
1987-06-16 09:30:00-04:00    2.0
2000-06-21 09:30:00-04:00    2.0
2005-02-28 09:30:00-05:00    2.0
2014-06-09 09:30:00-04:00    7.0
2020-08-31 09:30:00-04:00    4.0
Name: Stock Splits, dtype: float64

In [15]:
dict(ticker.fast_info)

{'currency': 'USD',
 'dayHigh': 339.6400146484375,
 'dayLow': 333.04998779296875,
 'exchange': 'NMS',
 'fiftyDayAverage': 320.1421990966797,
 'lastPrice': 338.9800109863281,
 'lastVolume': 34379725,
 'marketCap': 4947135296736.45,
 'open': 335.2799987792969,
 'previousClose': 334.8,
 'quoteType': 'EQUITY',
 'regularMarketPreviousClose': 336.1300048828125,
 'shares': 14594180000,
 'tenDayAverageVolume': 49158440,
 'threeMonthAverageVolume': 53449420,
 'timezone': 'America/New_York',
 'twoHundredDayAverage': 286.3411993408203,
 'yearChange': 0.31259771363646494,
 'yearHigh': 344.57000732421875,
 'yearLow': 243.4199981689453}